# Site settings
title: Titanium Creek Consulting
email: info@titaniumcreek.com
description: "Small Business and Restaurant and IT Consulting. Custom Designed Embedded Computing Solutions."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://titaniumcreek.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
